### ISSUE TITLE
Add support for calling Functions in Strings [Puppet 4]

### ISSUE THREAD

**Issue by PierreR** [bartavelle/language-puppet#199]
```
notify { 'need_coffee':
  message => "I need a cup of coffee. Remind me in ${fqdn_rand(10)} minutes.",
}
```

**Comment by bartavelle** [comment]
This is a large feature, and I will certainly not have time to implement it in the foreseeable future ...

**Comment by bartavelle** [comment]
This is tricky because there are two use cases:

 * `${foo}`, where it should be interpreted as variable `$foo`
 * `${foo[$bar]}`, where it should be interpreted as `$foo[$bar]`
 * `${foo($bar)}`, where it should be interpreted as `foo($bar)`

Perhaps the simplest solution would be to add the full expression parser after `try simpleIndexing` and `try rvariable` on lines 204-207 of the parser.

**Comment by bartavelle** [comment]
This is really horrible:

    "${::interfaces.split(',')[3]}"

**Comment by bartavelle** [comment]
This does't handle the case where you do arbitrary stuff to a variable, but should parse most expressions. To be toroughly tested!

**Comment by PierreR** [comment]
This is broken now:
```
class test {
  exec {
    "test":
      command     => "test",
      onlyif      => "grep '^${sanitised_title}$'",
  }
}
```
```
puppetresources --parse test.pp
puppetresources: parse error:ParseError {errorPos = SourcePos {sourceName = "test.pp", sourceLine = Pos 5, sourceColumn = Pos 49} :| [], errorUnexpected = fromList [Tokens ('\'' :| "")], errorExpected = fromList [Tokens (':' :| ":"),Tokens ('{' :| "")], errorCustom = fromList []}
CallStack (from HasCallStack):
  error, called at progs/PuppetResources.hs:374:24 in main:Main

```

**Comment by bartavelle** [comment]
Just pushed a change that should fix that.

**Comment by PierreR** [comment]
Doesn't break anymore in any obvious way. Thanks.
