### ISSUE TITLE
Implement a strict and a permissive mode in the interpreter

### ISSUE THREAD

**Issue by bartavelle** [bartavelle/language-puppet#86]
This would allow adding features I have been reluctant to add as they are antipatterns. It is likely that a few combinators would be enough to work properly.

**Comment by PierreR** [comment]
Ok I have just renamed `m` into `edgemap` for clarity sake.

Then I have realized that `edgemap` is only used for exported resources or with the flag `--JSON`. Is this correct ?

I am probably missing something because on my catalogs even with `--JSON` enabled the array `edges` seems to be empty all the time.

Any idea ?

**Comment by bartavelle** [comment]
I might be wrong but I think they are just integrated with the resources, as puppet seems to allow both ways of transmitting relationships ... but I didn't reverse engineer this, so I might be wrong.
